### ISSUE TITLE
Make PillString case insensitive

### ISSUE THREAD

**Issue by livingsilver94** [dmarkham/enumer#21]
It would be useful to perform string -> enum conversion in a case-insensitive fashion. While I could convert my string to lowercase and have all of my values lowercase as well, some of them are acronyms which looks ugly if not written with capital letters.

**Comment by dmarkham** [comment]
Can you show me a sample of what your trying to do?

**Comment by livingsilver94** [comment]
```go
type Pill int
const (
	Placebo Pill = iota
	IDK
)

```
Now, `IDK.String()` returns `"IDK"` if no transformation is performed, and that's OK, but if I wanted to do this:
```go
myPill := PillString("idk")
```
I would get an error because `"idk"` is lowercase. Suppose that the string comes from a CLI command: some users could write "idk", while others could write "IDK". I don't want to transform every pill to uppercase though because Placebo must stay as it is. 
Same rationale for Placebo, even: some could write "Placebo", others "placebo".

**Comment by dmarkham** [comment]
So I like the feature. I do not yet like my options on how I would implement this.

I want to keep things compatible with people relying on case-sensitivity not matter how silly that sounds.

I'll see what a patch will look like. Unless someone get there first.

**Comment by dmarkham** [comment]
@livingsilver94  I need more testing on this. But this seems like the cleanest way to pull this together.

**Comment by livingsilver94** [comment]
Thank you for implementing it :+1:
