### ISSUE TITLE
The err of func %[1]sString(s string) print a lower case of string

### ISSUE THREAD

**Issue by Maxence1** [dmarkham/enumer#43]
Hi team, 

I was trying to do some unhappy path test case using 
`//go:generate enumer -type=BusinessType -json -transform upper`

And when I test a **_"does not belong to BusinessType values"_** case:
I entered ABC, and expect to get **_"ABC does not belong to BusinessType values",_** 
but what I get is **_"abc does not belong to BusinessType values"_**

I think it's because the generated function **_BusinessTypeString_** transformed it into lower case, it's not impacting the code logic, but my test case becomes a little weird:
```
Input: "ABC"
Output: "abc does not belong to BusinessType values"
```

The question is, is there any way to generate without the toLower() transform in function **_BusinessTypeString_**?

Many thanks!

Best regards,

**Comment by Maxence1** [comment]
![image](https://user-images.githubusercontent.com/12404438/114651558-cbdc8400-9d16-11eb-891a-e338b6d533eb.png)

**Comment by dmarkham** [comment]
Interesting I never thought about this. I feel like it should return the in the error message what ever you pass in. I'll poke around this and see if I can not come up with a patch!

**Comment by dmarkham** [comment]
@Maxence1  do you have a change to have a look at this to see if it meets your needs?

**Comment by dmarkham** [comment]
All merged in and should be working as you expected now!
