### ISSUE TITLE
Fork force use for go generate

### ISSUE THREAD

**Issue by abonec** [dmarkham/enumer#45]
Now we have two libraries with similar features but not the same. And when I add annotations like 
```
//go:generate enumer -type=From -json -transform=snake
```
Binary can be from any of them and result can be different. Is there any way to make sure that code will be generated only by your binary? For example, add different binary name for ensure or some other tricks that provide incompatibility with original version?

**Comment by dmarkham** [comment]
This is one way to do it
```
//go:generate go run github.com/dmarkham/enumer  -type=From -json -transform=snake
```

**Comment by dmarkham** [comment]
Let me know how this works for you.

**Comment by abonec** [comment]
It is works, but Goland can't recognize that hack =(
![image](https://user-images.githubusercontent.com/240587/130814822-1d5b5b47-89e5-430d-ab43-acdcda66574a.png)
