### ISSUE TITLE
feature request: integration with validator/gin bindings

### ISSUE THREAD

**Issue by mikwys** [dmarkham/enumer#49]
Firstly, I'd like to thank you for great work, I found enumer really helpful!
---
I am not sure about proper solution, however I think that may be doable by another flag/parameter.

In perfect scenario it would either implement validator interface, or return validator.ValidationErrors. 
If not, maybe there is possibility to generate helper validator functions to bind for API models.

**Comment by dmarkham** [comment]
I do not really want to bring in any external  libraries, or external types, people rely on this library to not introduce new things into their code base.   We currently pull in 4 libraries and 3 of them are from golang.org, I would like to remove them all if I could.
