### ISSUE TITLE
Enable interoperability with ent

### ISSUE THREAD

**Issue by mvrahden** [dmarkham/enumer#50]
Hi, to improve interoperability with [ent](github.com/ent/ent) and support its enum type-safety, I'd propose to add the `Values() []string` method (from the [EnumValues interface](https://pkg.go.dev/entgo.io/ent/schema/field#EnumValues)) to the generated enum types, next to `String() string`.
This feature should likely be opt-in, so it would be beneficial to add a flag for it. I'd propose `-values` (or `-valuesFunc`) flag.

I've seen, there is already a generated `***Strings() []string`-func, which would just need to be wrapped by the `Values() []string` method in question.

@dmarkham Would you be open for a PR for this?

An Example:
```go
func (Pill) Values() []string {
  return PillStrings()
}
```

P.S.: I understand there's a potential for confusion, due to the pre-existing `PillValues() []Pill` function. But to have typesafety with enums in ent, this proposal is the only way to go from what I see.

**Comment by dmarkham** [comment]
I think a new flag yo add this method would be just fine.

**Comment by mvrahden** [comment]
@dmarkham pls bump version, so that the changes make it into the release. Thanks!
